In [40]:
 # imports
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
# import matplotlib.pyplot as plt
import os
from pathlib import Path
from dotenv import load_dotenv

In [41]:
 # Read the Mapbox API key
load_dotenv()
map_box_api = os.getenv("mapbox")
px.set_mapbox_access_token(map_box_api)

#  Import Data

In [42]:
 # Read the census data into a Pandas DataFrame
file_path = Path("Data/sfo_neighborhoods_census_data.csv")
sfo_data = pd.read_csv(Path("Data/sfo_neighborhoods_census_data.csv"), header=0)
# sfo_data = pd.read_csv(file_path, index_col="year")
sfo_data.head()


# Import the necessary CSVs to Pandas DataFrames
file_path1 = Path("Data/neighborhoods_coordinates.csv")
sfo_loc_data = pd.read_csv(file_path1, header=0)
# sfo_data = pd.read_csv(file_path, index_col="year")
sfo_loc_data.head()

      Neighborhood        Lat         Lon
0     Alamo Square  37.791012 -122.402100
1       Anza Vista  37.779598 -122.443451
2          Bayview  37.734670 -122.401060
3  Bayview Heights  37.728740 -122.410980
4   Bernal Heights  37.728630 -122.443050

In [43]:
# Calculate the mean number of housing units per year (hint: use groupby) 
# housing_units_per_year
sfo_data1 = sfo_data.reset_index()
num_of_housing_unit = sfo_data1[["housing_units", "year"]]
avg_unit_per_year = num_of_housing_unit.groupby("year").sum().reset_index()
avg_unit_per_year


## Average Housing Costs in San Francisco Per Year
# Calculating the average sale price per square foot and average gross rent
avg_cost =sfo_data.groupby("year").mean().reset_index()
avg_cost =avg_cost[["year","sale_price_sqr_foot","gross_rent"]]
avg_cost

#Average Sales Price Per Year."""
sale_price_sqr_foot = avg_cost[["year","sale_price_sqr_foot"]]

#Average Gross Rent in San Francisco Per Year."""
gross_rent = avg_cost[["year","gross_rent"]]
gross_rent

## Average Prices by Neighborhood
# Creating a dataframe to for the mean value
avg_by_neigh = sfo_data.groupby(["year","neighborhood"]).mean().reset_index()
avg_by_neigh .head(10)


#  The Top 10 Most Expensive Neighborhoods

sfo_data2 = sfo_data[['neighborhood','sale_price_sqr_foot','housing_units','gross_rent']]
avg_sfo_by_neigbhoor = sfo_data2.groupby(["neighborhood"]).mean().reset_index()
avg_sfo_by_neigbhoor.head(10)
Ten_most_exp=avg_sfo_by_neigbhoor.nlargest(10,['sale_price_sqr_foot']).reset_index()
Ten_most_exp

#  Comparing cost to purchase versus rental income
 # Fetch the previously generated DataFrame that was grouped by year and neighborhood 
avg_sfo_by_year1 = sfo_data.groupby(["year","neighborhood"]).mean().reset_index()

# Neighborhood Map
# Calculate the mean values for each neighborhood

sfo_data1= sfo_data[["neighborhood","sale_price_sqr_foot","housing_units","gross_rent"]]
avg_per_neigh =sfo_data1.groupby(["neighborhood"]).mean()
avg_per_neigh.head(10)

# Concatenate data - average values with the neighborhood locations
sfo_data_with_loc = (
    pd.concat([sfo_loc_data, avg_per_neigh], axis=1).dropna().reset_index())
sfo_data_with_loc.head(3)

#sfo_data_with_loc.set_index(sfo_data_with_loc['Neighborhood'], inplace=True)

sfo_data_with_loc =sfo_data_with_loc[["Neighborhood","Lat","Lon","sale_price_sqr_foot","housing_units",
                                      "gross_rent"]]

# Rename columns to be 'num_sales' and 'num_foreclosures'
sfo_data_with_loc.columns = ["Neighborhood","Latitude","Longitude","sale_price_sqr_foot","housing_units","gross_rent"]
sfo_data_with_loc.head(10)

## Cost Analysis - Optional Challenge
### Creating a DataFrame showing the most expensive neighborhoods in San Francisco by year
# Fetch the data from all expensive neighborhoods per year.
df_expensive_neighborhoods_per_year = sfo_data[sfo_data["neighborhood"].isin(Ten_most_exp["neighborhood"])]
df_expensive_neighborhoods_per_year.head(10)

### Create a sunburst chart to conduct a costs analysis of most expensive neighborhoods in San Francisco per year
df_expensive_neighborhoods_per_year
df_expensive_neighborhoods_per_year = sfo_data[sfo_data["neighborhood"].isin(Ten_most_exp["neighborhood"])]

sfo_data_with_loc.head(3)

Empty DataFrame
Columns: [Neighborhood, Latitude, Longitude, sale_price_sqr_foot, housing_units, gross_rent]
Index: []

## Panel Visualizations